### ISSUE TITLE
[examples/chat] Why do peers have to be their own friends?

### ISSUE THREAD

**Issue by adizere** [commonwarexyz/monorepo#103]
### Asymmetry in friend set

Suppose I have the following network of 2 friends:

> Bootstrap peer / friend 1
> 
> ```sh
> cargo run --release -- --me=1@9001 --friends=1,2
> ```
> 
> Friend 2
> 
> ```sh
> cargo run --release -- --me=2@9002 --friends=1 --bootstrappers=1@127.0.0.1:9001
> ```

Then every 3 seconds or so, friend 2 will croak and restart

> [10/03 07:23:29|DEBUG] commonware_p2p::authenticated::actors::tracker::actor => failed to handle bit vector (error="BitVecExtraBit")
[10/03 07:23:29|INFO] commonware_p2p::authenticated::actors::spawner::actor => peer shutdown (error="PeerKilled(\"ff87a0..
[10/03 07:23:29|DEBUG] commonware_p2p::authenticated::actors::router::actor => peer released (peer="ff87a0..

Friend 1 will also report this as debug messages:

> [10/03 07:24:29|INFO] commonware_p2p::authenticated::actors::spawner::actor => peer shutdown (error="ReceiveFailed(StreamClosed)" peer="191fc38f134aaf1b7f
[10/03 07:24:29|DEBUG] commonware_p2p::authenticated::actors::router::actor => peer released (peer="191fc38f134aaf1b7fdb1f86330b9d03e94bd4ba884f490389de96

Thanks to retries, the two friends will re-connect after each failure of friend 2.

## Symmetry

Interestingly, if the 2 peers are symmetric in their friend set, then the error no longer appears. By symmetric I mean that:
* peer 1 is friend with 2 (not with itself)
* peer 2 is friend with 1 (not with itself)

> Bootstrap peer / friend 1
> 
> ```sh
> cargo run --release -- --me=1@9001 --friends=2
> ```
> 
> Friend 2
> 
> ```sh
> cargo run --release -- --me=2@9002 --friends=1 --bootstrappers=1@127.0.0.1:9001
> ```

No error noticed in logs. The chat works as expected as far as I can tell.

## Questions

* Why does peer 2 have to have itself as a friend to avoid the error? And why does the error disappear when peer 1 is not his own friend?
* Unrelated to the scenarios above -- does commonware have support to [discover](https://github.com/commonwarexyz/monorepo/blob/ee0b909129c75153a5f12ef062ed9cae9e29475a/examples/chat/src/main.rs#L161-L165) new peers joining the network? More specifically: Suppose that peer 2 uses peer 1 for bootstrap, and that peer 3 uses peer 2 for bootstrap, then can commonware provide to peer 1 dialing information related to peer 3 (and provide to peer 3 dialing information related to peer 1)?

**Comment by adizere** [comment]
> Unrelated to the scenarios above -- does commonware have support to [discover](https://github.com/commonwarexyz/monorepo/blob/ee0b909129c75153a5f12ef062ed9cae9e29475a/examples/chat/src/main.rs#L161-L165) new peers joining the network? More specifically: Suppose that peer 2 uses peer 1 for bootstrap, and that peer 3 uses peer 2 for bootstrap, then can commonware provide to peer 1 dialing information related to peer 3 (and provide to peer 3 dialing information related to peer 1)?

I think I found the answer is: This is only possible if peer 1 knows the pubkey of peer 2 and peer 3 (and the other two peers respectively each know the pub keys of the others). I think this model makes sense. It assumes (valid assumption) that peers know some authentication information (and a bootstrap node) for a network they want to join. The model was not intuitive to me, but as I understand it now it makes a lot of sense.

**Comment by patrick-ogrady** [comment]
During startup, `commonware-chat` registers the specified "friends" (i.e. peers) at `index=0`:  https://github.com/commonwarexyz/monorepo/blob/ee0b909129c75153a5f12ef062ed9cae9e29475a/examples/chat/src/main.rs#L161-L165

As documented, peer discovery relies heavily on the assumption that peers are known at a given index: https://github.com/commonwarexyz/monorepo/blob/ee0b909129c75153a5f12ef062ed9cae9e29475a/p2p/src/authenticated/mod.rs#L91-L133

I failed to mention in those docs, however, that it is also assumed that the list of peers at a given index is synchronized. I'll add that now.

**Comment by patrick-ogrady** [comment]
> Interestingly, if the 2 peers are symmetric in their friend set, then the error no longer appears. 

Regarding your point on symmetry, all that we can check on a bit vector is that its length is expected. In your example, the length is expected and your directly dial a peer (2 dialing 1) that explicitly whitelists you. To prevent this issue, we could add a hash to these messages (over all members at an index to detect this).

**Comment by patrick-ogrady** [comment]
> peer 1 is friend with 2 (not with itself)
> peer 2 is friend with 1 (not with itself)

As for why this works, a peer will always accept a connection from someone that is in the set of allowed peers (even if it itself is not). I'm not sure if this should be considered a bug or not as running some process on `commonware-p2p` that is meant to connect to nothing seems useless (but semantically may be incorrect).

Will need to ponder this. As mentioned above, the only reason you need to include yourself is to ensure peer discovery works right (as bits are sent over a sorted index...we could always remove ourself from a message but that would mean recreating the bitvec each time).

**Comment by patrick-ogrady** [comment]
> Unrelated to the scenarios above -- does commonware have support to [discover](https://github.com/commonwarexyz/monorepo/blob/ee0b909129c75153a5f12ef062ed9cae9e29475a/examples/chat/src/main.rs#L161-L165) new peers joining the network? More specifically: Suppose that peer 2 uses peer 1 for bootstrap, and that peer 3 uses peer 2 for bootstrap, then can commonware provide to peer 1 dialing information related to peer 3 (and provide to peer 3 dialing information related to peer 1)?

Yes, you can run a chat example where you can see this working (where you bootstrap each terminal window of a new peer).

`commonware-p2p::authenticated` is documented extensively here: https://github.com/commonwarexyz/monorepo/blob/ee0b909129c75153a5f12ef062ed9cae9e29475a/p2p/src/authenticated/mod.rs#L1-L229

**Comment by patrick-ogrady** [comment]
> I think I found the answer is: This is only possible if peer 1 knows the pubkey of peer 2 and peer 3 (and the other two peers respectively each know the pub keys of the others). I think this model makes sense. It assumes (valid assumption) that peers know some authentication information (and a bootstrap node) for a network they want to join. The model was not intuitive to me, but as I understand it now it makes a lot of sense.

As mentioned earlier, yeah it is assumed in `commonware-p2p::authenticated` that all participants know the public keys of the other peers they want to connect to (not necessarily their IPs). As I also mentioned above, it assumes synchronization of this list at each registered index (and I had not mentioned that clearly).

**Comment by patrick-ogrady** [comment]
Thanks for diving in and asking some good questions!

**Comment by adizere** [comment]
Appreciate the thorough answers. I'm periodically playing with various primitives in the monorepo and will likely come back with other Qs, cheers!
