### ISSUE TITLE
[stream] Use milliseconds or nanoseconds instead of seconds in `Handshake.timeout`

### ISSUE THREAD

**Issue by BrendanChou** [commonwarexyz/monorepo#183]
Currently, timestamps for timeout (and clock-synchrony) purposes are floored to the nearest second, which can cause unexpected issues due to rounding. For example, a (reasonable) synchrony bound of 500 milliseconds gets rounded to 0 duration, which can be considered unexpected behavior.

The timestamp is already `uint64` type in the `wire.proto`. For practical time values, this stores:
- second timestamps in 5 bytes
- millisecond timestamps in 6 bytes
- nanosecond timestamps in 9 bytes
  - in this case, consider using the proto type `fixed64` instead, which uses 8 bytes and the encoding/decoding should be faster

**Comment by patrick-ogrady** [comment]
When this change is made, we should take the opportunity to add more testing on this path. With a 1s synchrony bound, a handshake started close to the second boundary will almost always fail (as the timestamp used will be floored).
