### ISSUE TITLE
[cryptography] Fix theoretical data/hash collision

### ISSUE THREAD

**Issue by BrendanChou** [commonwarexyz/monorepo#213]
There is a theoretical collision issue in crypto `sign(data)/verify(data)` because `data = namespace + message` where namespace can include a suffix or not.

So the following two things result in the same hash:
```
namespace: "my-application"
message: "/IPuserdata"
```
```
namespace: "my-application/IP"
message: "userdata"
```

Therefore to be safe, I think data should also include "delimiter information". This could either be:
- a byte of data between namespace and message where the byte's value is a value NEVER found in namespace, maybe something like 0x00.
- a length encoding of either namespace or message (just has to be one or the other consistently). I'm thinking length-encode  the namespace and require that namespace is never more than 255 in length

**Comment by patrick-ogrady** [comment]
As discussed, let's do the latter (byte-long length encoding that prefixes the namespace).
