### ISSUE TITLE
[security] Enable overflow checks via configuring profiles

### ISSUE THREAD

**Issue by johnsaigle** [commonwarexyz/monorepo#291]
By default, Rust code will cause panics during integer overflow/underflow _in test builds_ but will wrap silently for release builds.

Given the security and reliability requirements of this project, overflows should cause panics rather than wrap. 

https://doc.rust-lang.org/cargo/reference/profiles.html#overflow-checks

**Comment by antonio-hickey** [comment]
I'd like to pick this one up

**Comment by patrick-ogrady** [comment]
> I'd like to pick this one up

You got it 🫡
