### ISSUE TITLE
[runtime/deterministic] Add Metrics

### ISSUE THREAD

**Issue by patrick-ogrady** [commonwarexyz/monorepo#87]
Add metric for tracking bandwidth usage by socket and for tasks spawned.

For deterministic, we can also add number of polls.

**Comment by malik672** [comment]
@patrick-ogrady assign me

**Comment by patrick-ogrady** [comment]
You got it 🫡.

I've established a pattern that I'd like to carry forward from `p2p::authenticated`. Let me know if you prefer a different approach.

**Comment by malik672** [comment]
that was fast, will take a look at it
