### ISSUE TITLE
[cryptography] Add Hardcoded Test Vectors for Signature Schemes

### ISSUE THREAD

**Issue by patrick-ogrady** [commonwarexyz/monorepo#89]
The RFC for `ed25519` (https://datatracker.ietf.org/doc/html/rfc8032#section-7.1) specifies a number of test cases that any implementation must handle. We should add these to ensure our implementation doesn't silently regress (verification of signatures in our tests is performed by the same implementation we are testing).

There is no RFC for `bls12381`  that provides a list of tests an implementation must handle. So, we'll need to generate our own cases and hardcode them for both EOA and Threshold signing (for the same reason as above). There may be some examples of message/signatures in popular BLS crates.

**Comment by mahmudsudo** [comment]
can i take on this on this issue ?

**Comment by patrick-ogrady** [comment]
You bet! Assigning you now.

**Comment by mahmudsudo** [comment]
on it
