### ISSUE TITLE
[p2p/simulated] Add Metrics

### ISSUE THREAD

**Issue by patrick-ogrady** [commonwarexyz/monorepo#90]
Like in `p2p::authenticated`, we should add metrics to meter common functionality (as it could be useful to assert against in a test).

**Comment by patrick-ogrady** [comment]
@najeal can you comment here so that I can assign this original one to you (to avoid any confusion)?

**Comment by patrick-ogrady** [comment]
Related: #96

**Comment by najeal** [comment]
👋 yep !
