### ISSUE TITLE
[p2p/simulated] Add support for multiplexing

### ISSUE THREAD

**Issue by patrick-ogrady** [commonwarexyz/monorepo#96]
Related: https://github.com/commonwarexyz/monorepo/pull/93

We should replicate the ability to register multiple channels over a single connection, like in `commonware-p2p::authenticated`. I spaced on this functionality when working on `commonware-p2p::simulated`. 🤦 

I don't think we need to mirror the `register` function directly (https://github.com/commonwarexyz/monorepo/blob/9109b98702651b5521104251f98871160efcf396/p2p/src/authenticated/network.rs#L97-L122) at first but could in the future (and define as a trait).

**Comment by patrick-ogrady** [comment]
I don't think you'll need to use the channels struct from `authenticated` and believe we can replicate the similar capability much more simply with `simulated` (can have a map of `mpsc::channel` per registered peer and apply same link characteristics to all channels).

**Comment by malik672** [comment]
will do this

**Comment by najeal** [comment]
@malik672 it you don't see any problem I would like to look at this issue as mentioned in the original comment (https://github.com/commonwarexyz/monorepo/pull/93#issuecomment-2377862066) 🙂

**Comment by patrick-ogrady** [comment]
@najeal is going to jam on this one. It was from the original PR he was taking a stab at 👍 .

(My bad for not calling out in description)

**Comment by patrick-ogrady** [comment]
> will do this

Left some ideas on the PR you were working on @malik672 (will create an issue once you reply there).

**Comment by najeal** [comment]
I'm looking at what is existing.
I am not sure to get the target of these new channels to create.
I see one channel existing for each PublicKey.
We want to add possibility to add more channel for a unique PublicKey. How these channels are supposed to act together?

**Comment by patrick-ogrady** [comment]
Hi @najeal, I need this functionality to start testing `commonware-consensus` and am going to take it over.

We can find a new task for you to work on after I take care of this and you complete #90.
